// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// knox
List knox(NumericVector x, NumericVector y, NumericVector time, double sigma, double tau);
RcppExport SEXP knox_knox(SEXP xSEXP, SEXP ySEXP, SEXP timeSEXP, SEXP sigmaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< double >::type tau(tauSEXP );
        List __result = knox(x, y, time, sigma, tau);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// knox_mc
List knox_mc(NumericVector x, NumericVector y, NumericVector time, double sigma, double tau, int perm = 999);
RcppExport SEXP knox_knox_mc(SEXP xSEXP, SEXP ySEXP, SEXP timeSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP permSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< double >::type tau(tauSEXP );
        Rcpp::traits::input_parameter< int >::type perm(permSEXP );
        List __result = knox_mc(x, y, time, sigma, tau, perm);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// iknox_mc
List iknox_mc(NumericVector x, NumericVector y, NumericVector time, double sigma, double tau, int perm = 999);
RcppExport SEXP knox_iknox_mc(SEXP xSEXP, SEXP ySEXP, SEXP timeSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP permSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< double >::type tau(tauSEXP );
        Rcpp::traits::input_parameter< int >::type perm(permSEXP );
        List __result = iknox_mc(x, y, time, sigma, tau, perm);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// st_link
DataFrame st_link(NumericVector x, NumericVector y, NumericVector time, double ds, double dt);
RcppExport SEXP knox_st_link(SEXP xSEXP, SEXP ySEXP, SEXP timeSEXP, SEXP dsSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP );
        Rcpp::traits::input_parameter< double >::type ds(dsSEXP );
        Rcpp::traits::input_parameter< double >::type dt(dtSEXP );
        DataFrame __result = st_link(x, y, time, ds, dt);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
