# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knox <- function(x, y, time, sigma, tau) {
    .Call('knox_knox', PACKAGE = 'knox', x, y, time, sigma, tau)
}

knox_mc <- function(x, y, time, sigma, tau, perm = 999L) {
    .Call('knox_knox_mc', PACKAGE = 'knox', x, y, time, sigma, tau, perm)
}

iknox_mc <- function(x, y, time, sigma, tau, perm = 999L) {
    .Call('knox_iknox_mc', PACKAGE = 'knox', x, y, time, sigma, tau, perm)
}

st_link <- function(x, y, time, ds, dt) {
    .Call('knox_st_link', PACKAGE = 'knox', x, y, time, ds, dt)
}

