# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname knox
#' @title Original Knox test
#' @description Original Knox test
#' @param x Longitude, should be projected to a planar system.
#' @param y Latitude, should be projected to a planar system.
#' @param time time column.
#' @param sigma a distance in space.
#' @param tau a distance in time.
#' @return A knox statistic, which is the number of pairs of points found in a given space-time distance.
#' @references \strong{Knox, E. (1964)}. \emph{The detection of space-time interactions.} Journal of the Royal Statistical Society. Series C (13(1), 25-30.
#' 
#' \strong{Tango, T. (2010)}. \emph{Statistical methods for disease clustering. Springer.}
#' @export
knox <- function(x, y, time, sigma, tau) {
    .Call('knox_knox', PACKAGE = 'knox', x, y, time, sigma, tau)
}

#' @rdname knox_simulation 
#' @title Knox test with Monte Carlo simulation
#' @description Performing Knox statistics with Monte Carlo simulation
#' @param x Longitude, should be projected to a planar system.
#' @param y Latitude, should be projected to a planar system.
#' @param time time column.
#' @param sigma a distance in space.
#' @param tau a distance in time.
#' @param perm Number of simulations. Default is 999
#' @return \item{knox}{Knox statistic, which is the number of pairs of points found in a given space-time distance.} 
#' \item{p_value}{p-value calculated from simulation} 
#' \item{RR}{Relative Risk - calculated by observed value (Knox statistics) divided by mean of simulated values}
#' @export
knox_mc <- function(x, y, time, sigma, tau, perm = 999L) {
    .Call('knox_knox_mc', PACKAGE = 'knox', x, y, time, sigma, tau, perm)
}

iknox_mc <- function(x, y, time, sigma, tau, perm = 999L) {
    .Call('knox_iknox_mc', PACKAGE = 'knox', x, y, time, sigma, tau, perm)
}

#' @rdname st_links
#' @title space-time link
#' @description Create space-time links between two points from a given space and time distance.
#' @param x Longitude - should be projected to a planar system.
#' @param y Latitude - should be projected to a plannar system.
#' @param time time
#' @param ds a distance in space.
#' @param dt a distance in time.
#' @return A data frame with \item{Xo, Yo}{ X, Y of the starting point}
#' \item{Xd, Yd}{ X, Y of the ending point}
#' @export
st_link <- function(x, y, time, ds, dt) {
    .Call('knox_st_link', PACKAGE = 'knox', x, y, time, ds, dt)
}

